version: 2
jobs:
  test:
    docker:
      - image: ubuntu:14.04
    environment:
      TERM: dumb
    steps:
      - checkout
      - run: |
          apt-get install -y sudo
          apt-get -qq update; apt-get -y install git
          git clone --single-branch --branch develop https://github.com/aaronkjones/noobs-term.git
          cd noobs-term
          chmod +x noobs-term.sh
          sh noobs-term.sh
workflows:
  version: 2
  test:
    jobs:
      - test