version: 2
jobs:
  test:
    docker:
      - image: ubuntu:14.04
    steps:
      - checkout
      - run: |
          git clone --single-branch --branch develop https://github.com/aaronkjones/noobs-term.git
          cd noobs-term
          chmod +x noobs-term.sh
          sh noobs-term.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - test